// 공격자가 자주 악용하는 실행 파일(LOLBin·유틸리티) 카탈로그.
// 실행 이력에서 이런 도구를 놓치지 않도록 짧은 설명을 붙인다.
// 표시는 힌트일 뿐이며, 실행 자체가 악성이라는 뜻은 아니다.
export const EXECUTABLE_NOTES: Record<string, string> = {
  "attrib.exe": "파일 속성 변경",
  "csc.exe": "C# 컴파일러",
  "cvtres.exe": "리소스 변환기 · C# 컴파일 시 동반 실행",
  "schtasks.exe": "작업 스케줄러 등록",
  "wscript.exe": "스크립트 실행 호스트",
  "cscript.exe": "콘솔 스크립트 호스트",
  "mshta.exe": "HTA 스크립트 실행",
  "rundll32.exe": "DLL 함수 실행",
  "regsvr32.exe": "DLL 등록·실행",
  "certutil.exe": "인증서 관리",
  "bitsadmin.exe": "BITS 전송 도구",
  "powershell.exe": "파워셸",
  "powershell_ise.exe": "파워셸 편집기",
  "pwsh.exe": "파워셸 7",
  "cmd.exe": "명령 프롬프트",
  "wmic.exe": "WMI 명령 도구",
  "reg.exe": "레지스트리 편집",
  "sc.exe": "서비스 제어",
  "net.exe": "계정·공유 관리",
  "net1.exe": "계정·공유 관리",
  "netsh.exe": "네트워크 설정 변경",
  "whoami.exe": "현재 계정 확인",
  "tasklist.exe": "프로세스 목록 조회",
  "taskkill.exe": "프로세스 강제 종료",
  "vssadmin.exe": "볼륨 섀도 복사본 관리",
  "wevtutil.exe": "이벤트 로그 관리",
  "bcdedit.exe": "부팅 구성 변경",
  "cipher.exe": "디스크 완전 삭제 도구",
  "icacls.exe": "파일 권한 변경",
  "cacls.exe": "파일 권한 변경(구형)",
  "takeown.exe": "파일 소유권 획득",
  "robocopy.exe": "대량 파일 복사",
  "xcopy.exe": "파일 복사",
  "ftp.exe": "FTP 전송",
  "curl.exe": "파일 다운로드",
  "at.exe": "작업 예약(구형)",
  "msiexec.exe": "MSI 설치 실행",
  "installutil.exe": ".NET 설치 도구",
  "regasm.exe": ".NET 어셈블리 등록",
  "regsvcs.exe": ".NET 서비스 등록",
  "msbuild.exe": "빌드 도구",
  "forfiles.exe": "파일 반복 실행",
  "ntdsutil.exe": "AD 데이터베이스 덤프",
  "diskshadow.exe": "섀도 복사본 조작",
  "esentutl.exe": "ESE 데이터베이스 도구",
  "expand.exe": "압축 파일 추출",
  "extrac32.exe": "CAB 추출",
  "makecab.exe": "CAB 압축",
  "wbadmin.exe": "백업 관리",
  "quser.exe": "로그온 세션 조회",
  "qwinsta.exe": "RDP 세션 조회",
  "mstsc.exe": "원격 데스크톱 클라이언트",
  "rdpinput.exe": "RDP 세션 섀도잉 입력 제어",
  "psexec.exe": "원격 실행 도구",
  "psexec64.exe": "원격 실행 도구",
  "psexesvc.exe": "PsExec 원격 서비스",
  "procdump.exe": "프로세스 메모리 덤프",
  "procdump64.exe": "프로세스 메모리 덤프",
  "mimikatz.exe": "자격 증명 덤프 도구",
  "rclone.exe": "클라우드 대량 전송 도구",
  "7z.exe": "압축 도구",
  "7za.exe": "압축 도구",
  "rar.exe": "압축 도구",
  "winrar.exe": "압축 도구",
  "anydesk.exe": "원격 제어 도구",
  "teamviewer.exe": "원격 제어 도구",
  "ngrok.exe": "터널링 도구",
  "plink.exe": "SSH 터널 도구",
  "ssh.exe": "SSH 클라이언트",
  "sdelete.exe": "완전 삭제 도구",
  "sdelete64.exe": "완전 삭제 도구",
  "nltest.exe": "도메인 정보 조회",
  "dsquery.exe": "AD 조회",
  "adfind.exe": "AD 조회 도구",
  "systeminfo.exe": "시스템 정보 수집",
  "ipconfig.exe": "네트워크 구성 조회",
  "arp.exe": "ARP 캐시 조회",
  "nbtstat.exe": "NetBIOS 조회",
  "netstat.exe": "네트워크 연결 조회",
  "klist.exe": "Kerberos 티켓 조회",
  "cmdkey.exe": "저장된 자격 증명 관리",
  "mofcomp.exe": "MOF 컴파일러",
  "hh.exe": "HTML 도움말 실행",
  "wsl.exe": "리눅스 하위 시스템 실행",
};

/** 실행 파일 이름으로 카탈로그 설명을 찾는다. 없으면 빈 문자열. */
export function executableNote(name: string): string {
  return EXECUTABLE_NOTES[name.trim().toLowerCase()] ?? "";
}
